/**
 * LISTAS DE DATOS PARA SELECTORES
 * Basado en el PDF oficial y requisitos del sistema
 */

// Lista completa de países del mundo
export const PAISES = [
  'República Dominicana',
  'Estados Unidos',
  'Canadá',
  'México',
  'Guatemala',
  'Honduras',
  'El Salvador',
  'Nicaragua',
  'Costa Rica',
  'Panamá',
  'Cuba',
  'Haití',
  'Jamaica',
  'Puerto Rico',
  'Trinidad y Tobago',
  'Bahamas',
  'Barbados',
  'Argentina',
  'Bolivia',
  'Brasil',
  'Chile',
  'Colombia',
  'Ecuador',
  'Guyana',
  'Paraguay',
  'Perú',
  'Surinam',
  'Uruguay',
  'Venezuela',
  'España',
  'Francia',
  'Italia',
  'Alemania',
  'Reino Unido',
  'Portugal',
  'Países Bajos',
  'Bélgica',
  'Suiza',
  'Austria',
  'Grecia',
  'Irlanda',
  'Dinamarca',
  'Suecia',
  'Noruega',
  'Finlandia',
  'Polonia',
  'República Checa',
  'Hungría',
  'Rumania',
  'Bulgaria',
  'Croacia',
  'Serbia',
  'Rusia',
  'Ucrania',
  'China',
  'Japón',
  'Corea del Sur',
  'India',
  'Tailandia',
  'Vietnam',
  'Indonesia',
  'Filipinas',
  'Singapur',
  'Malasia',
  'Australia',
  'Nueva Zelanda',
  'Egipto',
  'Sudáfrica',
  'Nigeria',
  'Kenia',
  'Marruecos',
  'Argelia',
  'Túnez',
  'Israel',
  'Emiratos Árabes Unidos',
  'Arabia Saudita',
  'Turquía',
].join('|');

// Ritmos musicales según PDF (página 30)
export const RITMOS_MUSICALES = [
  'Bachata',
  'Baladas',
  'Blues',
  'Bolero',
  'Bosa Nova',
  'Celta',
  'Clasica',
  'Corrido',
  'Country',
  'Criollo',
  'Cumbia',
  'Disco',
  'Djent',
  'Dubstep',
  'Electronica',
  'Electro Pop',
  'Flamenco',
  'Folk',
  'Funk',
  'Garage Rock',
  'Gospel',
  'Grunge',
  'Hard Rock',
  'Heavy Metal',
  'Hip Hop',
  'House',
  'Indie',
  'Jazz',
  'K-Pop',
  'Merengue',
  'Perreo',
  'Polka',
  'Pop',
  'Punk',
  'Ranchera',
  'Rap',
  'Rap Rock',
  'Reggae',
  'Reggaeton',
  'Rock',
  'Rock and Roll',
  'Rock Psicodelico',
  'Rumba',
  'Rhythm and Blues',
  'Salsa',
  'Samba',
  'Ska',
  'Son',
  'Soul',
  'Swing',
  'Tango',
  'Techno',
  'Trash metal',
  'Trap',
  'Trova',
  'Vals',
  'Vallenato',
  'Epico o narrativo',
  'Lirico',
  'Dramatico',
  'Dembow',
  'Rock Alternativa',
  'College Rock',
  'Rock Gótico',
  'Shoegaze',
  'Anime',
  'Musica de Camara',
  'Opera',
  'Sinfónico',
  'Medieval',
  'Disney',
  'Drone',
].join('|');

// Géneros cinematográficos
export const GENEROS_CINEMATOGRAFICOS = [
  'Acción',
  'Aventura',
  'Ciencia Ficción',
  'Comedia',
  'Drama',
  'Fantasía',
  'Terror',
  'Suspenso',
  'Romance',
  'Musical',
  'Western',
  'Bélico',
  'Histórico',
  'Biográfico',
  'Animación',
  'Documental',
  'Noir',
  'Thriller',
  'Crimen',
  'Misterio',
  'Familiar',
  'Deportivo',
].join('|');

// Géneros para documentales
export const GENEROS_DOCUMENTALES = [
  'Histórico',
  'Naturaleza',
  'Científico',
  'Social',
  'Político',
  'Cultural',
  'Biográfico',
  'Musical',
  'Deportivo',
  'Educativo',
  'Investigativo',
  'Experimental',
].join('|');

// Géneros para fonogramas
export const GENEROS_FONOGRAMAS = [
  'Pop',
  'Rock',
  'Jazz',
  'Clásica',
  'Electrónica',
  'Hip Hop',
  'Reggaeton',
  'Salsa',
  'Merengue',
  'Bachata',
  'Baladas',
  'Regional Mexicano',
  'Tropical',
  'Urbano',
  'Folklore',
  'Blues',
  'Country',
  'R&B',
  'Soul',
  'Funk',
  'Metal',
  'Punk',
  'Indie',
  'Experimental',
  'Música del Mundo',
].join('|');

// Carácter de obra (común para varias categorías)
export const CARACTER_OBRA_BASE = [
  'Anónima',
  'Derivada',
  'Colaboración',
  'Individual',
  'Originaria',
  'Por Encargo',
  'Seudónima',
  'Obra Póstuma',
].join('|');

// Carácter de obra literaria
export const CARACTER_OBRA_LITERARIA = [
  'Inédita',
  'Publicada',
  'Originaria',
  'Derivada',
  'Individual',
].join('|');

// Carácter de obra para colecciones (sin "Derivada")
export const CARACTER_OBRA_COLECCION = [
  'Anónima',
  'Colaboración',
  'Individual',
  'Originaria',
  'Por Encargo',
  'Seudónima',
  'Obra Póstuma',
].join('|');

// Categoría de obra derivada musical (según PDF página 1)
export const CATEGORIA_OBRA_DERIVADA_MUSICAL = [
  'Bachata',
  'Baladas',
  'Blues',
  'Bolero',
  'Bosa Nova',
  'Celta',
  'Clasica',
  'Corrido',
  'Country',
  'Criollo',
  'Cumbia',
  'Disco',
  'Djent',
  'Dubstep',
  'Electronica',
  'Electro Pop',
  'Flamenco',
  'Folk',
  'Funk',
  'Garage Rock',
  'Gospel',
  'Grunge',
  'Hard Rock',
  'Heavy Metal',
  'Hip Hop',
  'House',
  'Indie',
  'Jazz',
  'K-Pop',
  'Merengue',
  'Perreo',
  'Polka',
  'Pop',
  'Punk',
  'Ranchera',
  'Rap',
  'Rap Rock',
  'Reggae',
  'Reggaeton',
  'Rock',
  'Rock and Roll',
  'Rock Psicodelico',
  'Rumba',
  'Rhythm and Blues',
  'Salsa',
  'Samba',
  'Ska',
  'Son',
  'Soul',
  'Swing',
  'Tango',
  'Techno',
  'Trash metal',
  'Trap',
  'Trova',
  'Vals',
  'Vallenato',
  'Epico o narrativo',
  'Lirico',
  'Dramatico',
  'Dembow',
].join('|');
